### ISSUE TITLE
Translation cannot handle strings containing {}

### ISSUE THREAD

**Issue by clemenskol** [boardpack/pydantic-i18n#218]
**Describe the bug**

If the text sent for translation contain special characters picked up by python's `format()`, this crashes the translation by raising `KeyError`

Cause is this line:

```
return self.source.gettext(key, locale).format(*placeholder_values)
```

more specifically the `.format(*placeholder_values)`

**To Reproduce**

1. Attempt to translate this string: `"test {foo}"`
2. Although there are no placeholders, the `.format()` will attempt to substitute variable `foo` which isn't provided, raising `KeyError`

### Environment

* OS: [e.g. Linux / Windows / macOS]: any
* pydantic-i18n version [e.g. 0.1.0]: latest main (0.4.0)

* Python version: any (e.g. 3.11.8)

**Comment by clemenskol** [comment]
note that a simple `{` in the input will already suffice.

This bug is particularly problematic if the input contains a string'ified dict, which will always contain a `{`

**Comment by dukkee** [comment]
Hello, @clemenskol It seems like the same issue as #216 And your fix #217 will cover it too

**Comment by dukkee** [comment]
Hello @clemenskol Could you provide more real examples please? Is it a correct case?
```python
{
    "en_US": {
        "Value error, test {bar} {'foo': 3}": "Field required",
    },
    "de_DE": {
        "Value error, test {bar} {'foo': 3}": "Feld erforderlich",
    },
}
```

**Comment by clemenskol** [comment]
actually no. there are other cases where the fix doesn't cover it. But I'm literally in the process of sending a pull request.

I wanted to keep them separate to fix separate bugs
