### ISSUE TITLE
Examples do not work for Pydantic 2

### ISSUE THREAD

**Issue by MartinSchmidt123** [boardpack/pydantic-i18n#228]
When creating a new project containing nothing but the example script, the output is not translated.

Even worse, the collected translations are wrong.

**To Reproduce**

1. `> pipenv install pydantic-i18n`
2. `> pipenv run python -c "import pydantic_i18n; print(pydantic_i18n.PydanticI18n.get_pydantic_messages(output='json'))" | jq`

    prints
    ```
    {
      "field required": "field required",
      "extra fields not permitted": "extra fields not permitted",
      "none is not an allowed value": "none is not an allowed value",
       [..]
    }
    ```

3. try to translated the generated "field required" via provided example script from Readme file (copied to main.py)

    `> pipenv run python main.py`
    Output:
    `[{'type': 'missing', 'loc': ('name',), 'msg': 'Field required', 'input': {}, 'url': 'https://errors.pydantic.dev/2.6/v/missing'}]`

### Environment

- annotated-types==0.6.0
- pydantic==2.6.3
- pydantic-i18n==0.4.1
- pydantic_core==2.16.3
- typing_extensions==4.10.0- 

* Python version: 3.11.8

### Additional context

The following commit changes the capitalization in the test case from "field required"  to "Field required":
https://github.com/boardpack/pydantic-i18n/commit/33f8d42592ad245904c2cc1b908d715a251523c2#diff-41d180f6f7233d175c2dfe36c45c4ea80eed4754fa7ed4eed46ccde1b2a778c7R12

"Field required" can be translated but knowing which strings have changed with pydantic 2 is difficult, especially since the generated/collected string are wrong.

**Comment by dukkee** [comment]
Hello, @MartinSchmidt123 Thank you for your issue, I really need to review the docs and refactor the examples.
Regarding the messages list, I will also take a look at it.

One of the last things I will add is an opportunity to search by the error type instead of the message (#223). I didn't find the final place of the messages in v2 (therefore the v1 module analysis is used), but the error type list is mentioned in the docs:

https://docs.pydantic.dev/2.6/errors/validation_errors

What do you think about it?

**Comment by MartinSchmidt123** [comment]
After some more digging I found the Pydantic 2 strings in 

- https://github.com/pydantic/pydantic-core/blob/main/src/errors/types.rs#L471 and 
- https://github.com/pydantic/pydantic-core/blob/main/src/errors/types.rs#L573

But I think translating error types is much more robust and prevents problems when they change the strings the next time.
It also is the way they do custom error messages in https://docs.pydantic.dev/latest/errors/errors/#customize-error-messages

**Comment by dukkee** [comment]
> After some more digging I found the Pydantic 2 strings in
> 
> * https://github.com/pydantic/pydantic-core/blob/main/src/errors/types.rs#L471 and
> * https://github.com/pydantic/pydantic-core/blob/main/src/errors/types.rs#L573
> 
> But I think translating error types is much more robust and prevents problems when they change the strings the next time. It also is the way they do custom error messages in https://docs.pydantic.dev/latest/errors/errors/#customize-error-messages

Thank you for your investigation so we can extract it in the following way:
```python
from pprint import pprint 
from pydantic_core._pydantic_core import list_all_errors

pprint(list_all_errors())
```

Regarding the link from the pydantic docs, it's exactly what I wrote in the previous message: instead of searching by the message as a key, it will be possible to search by the error type

**Comment by dukkee** [comment]
A correct message source was fixed in #229 and today/tomorrow I will fix the examples in the docs and release a new version

**Comment by dukkee** [comment]
@MartinSchmidt123 Examples were updated, and a new version was released. Please try again

**Comment by MartinSchmidt123** [comment]
@dukkee Thanks for your effort. I can confirm that it works for Pydantic 2.
