### ISSUE TITLE
Babel is not optional

### ISSUE THREAD

**Issue by tigrus** [boardpack/pydantic-i18n#27]
When you ignore babel dependency - whole project startup will fail. 

This line will try to import babel loader
https://github.com/boardpack/pydantic-i18n/blob/master/pydantic_i18n/__init__.py#L7

This line will burn application: 
https://github.com/boardpack/pydantic-i18n/blob/master/pydantic_i18n/loaders.py#L5

Please do not mark dependencies as optional, while they are not!

**Comment by dukkee** [comment]
Hello, @tigrus, oops, you are entirely right... I'm fixing it now, sorry

**Comment by dukkee** [comment]
@tigrus released, please recheck it on your side, it must be fine

**Comment by tigrus** [comment]
Looks fine now. Thanks for fast fix :)
