### ISSUE TITLE
Can not translate the errors, errors method does not exist

### ISSUE THREAD

**Issue by sehHeiden** [boardpack/pydantic-i18n#284]
I want to translate the error. Just the method to get the pydantic errors does not exist.

I tried:

```python
    loader = JsonLoader(PROJECT_PATH / "translations")
    tr = PydanticI18n(loader)


    with pytest.raises(ValidationError) as e:
        Configuration(**config)
    translated_errors = tr.translate(e.errors(), locale="de_DE")
```

Returns the error: AttributeError: 'ExceptionInfo' object has no attribute 'errors'

### Environment

* OS: Windows
* pydantic-i18n version 0.4.4:
* pydantic version: 2.8.2
* Python version: 3.9.13

**Comment by sehHeiden** [comment]
In Pytest:

e.value.errors() is needed!

**Comment by dukkee** [comment]
Hello @sehHeiden So what is your issue now?

Yes, you need to use the `e.value` instead of just `e` to access the exception object and then you can use the `errors` method.

**Comment by dukkee** [comment]
Hey @sehHeiden It's related more to the `pytest` than to the `pydantic-i18n` I think. Here is the description of this `value` attribute usage:
https://docs.pytest.org/en/7.1.x/how-to/assert.html#assertions-about-expected-exceptions
