### ISSUE TITLE
Wrong encoding with Russian letters using JsonLoader

### ISSUE THREAD

**Issue by Eclipsium** [boardpack/pydantic-i18n#7]
Wrong encoding with Russian letters using JsonLoader

![image](https://user-images.githubusercontent.com/31643737/128489561-5be3a990-19d0-44d4-bff4-ebeff143f2a9.png)

File have utf-8 encoding

![image](https://user-images.githubusercontent.com/31643737/128490004-47d47a6a-2408-436b-9085-813d8b798e98.png)

**Comment by Eclipsium** [comment]
I created my own loader, where I corrected the loading of a non-existent default key, and hardcoded the encoding, but I think it's worth adding it to __init__ method. Maybe it will be useful 

    def gettext(self, key: str, locale: str) -> str:
        if locale not in self.locales:
            raise ValueError(f"Locale '{locale}' wasn't found.")

        data = self.get_translations(locale)
        if not data.get(key):
            return key
        return data.get(key)

    def get_translations(self, locale: str) -> Mapping[str, str]:
        with open(os.path.join(self.directory, f"{locale}.json"),
                  encoding='utf-8') as fp:
            data: Dict[str, str] = json.load(fp)

        return data`

**Comment by dukkee** [comment]
Hello @Eclipsium, thank you very much for your issue. 
I checked the Russian locale example now on my machine and it works okay + if you check your `message` content you will see the strange prefix `body -> files ...`. Could you provide a full example, please?

**Comment by dukkee** [comment]
Regarding current key returning in the case when there isn't such key in the translations, it makes sense and will be added, thanks

**Comment by dukkee** [comment]
@Eclipsium as you don't show a full example, I close this issue. When you get time, then please reopen
